name: Test GitHub Feedback

on:
  repository_dispatch:  #gfg
    types: [trigger-test] # Lệnh này phải khớp với event_type trong file HTML

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MQTT Library
        run: pip install paho-mqtt

      - name: Run Feedback Script
        env:
          # Các biến này lấy từ GitHub Settings -> Secrets -> Actions
          MQTT_SERVER: ${{ secrets.f7a99425c8a34f23aba171e48336da3b.s1.eu.hivemq.cloud }}
          MQTT_USER: ${{ secrets.long140203 }}
          MQTT_PASS: ${{ secrets.Long140203 }}
        run: python test_feedback.py
