name: Sum Calculator Server

on:
  repository_dispatch:
    types: [calculate-sum]

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install paho-mqtt

      - name: Run Sum Script
        env:
          # Lấy 2 số từ payload của Web gửi lên
          INPUT_N1: ${{ github.event.client_payload.number1 }}
          INPUT_N2: ${{ github.event.client_payload.number2 }}
          MQTT_SERVER: ${{ secrets.MQTT_SERVER }}
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PASS: ${{ secrets.MQTT_PASS }}
        run: python sum_script.py
