name: Test GitHub Feedback

on:
  repository_dispatch:  #gfgdfa
    types: [trigger-test] # Lệnh này phải khớp với event_type trong file HTML

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install MQTT Library
        run: pip install paho-mqtt

      - name: Run Feedback Script
        env:
          # Các biến này lấy từ GitHub Settings -> Secrets -> Actions
          MQTT_SERVER: ${{ secrets.MQTT_SERVER }}
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PASS: ${{ secrets.MQTT_PASS }}
        run: python test_feedback.py
